tasks/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views


app_name = "tasks"

urlpatterns = [
    path("taskssearch/", views.TaskFilterView.as_view(), name="task_search"),
    path("projects/", views.ProjectList.as_view(), name="list_projects"),
    path("projects/create", views.ProjectCreateView.as_view(), name="create_project"),
    path("projects/<str:pk>", views.TaskListView.as_view(), name="list_task"),
    path(
        "projects/<str:pk>/update",
        views.ProjectUpdateView.as_view(),
        name="update_project",
    ),
    path(
        "projects/<str:pk>/delete",
        views.ProjectDeleteView.as_view(),
        name="delete_project",
    ),
    path(
        "projects/<str:pk>/tasks/create",
        views.TaskCreateView.as_view(),
        name="create_task",
    ),
    path(
        "projects/<str:pk>/tasks/<str:task_pk>/update",
        views.TaskUpdateView.as_view(),
        name="update_task",
    ),
    path(
        "projects/<str:pk>/tasks/<str:task_pk>/markascomplete",
        views.task_completed_view,
        name="mark_as_complete",
    ),
    path(
        "projects/<str:pk>/tasks/<str:task_pk>/delete",
        views.TaskDeleteView.as_view(),
        name="delete_task",
    ),
    path(
        "overduetasks/",
        views.TaskOverdueListView.as_view(),
        name="list_all_overdue_tasks",
    ),
    path(
        "overduetasks/<str:pk>",
        views.TaskOverdueListView.as_view(),
        name="list_overdue_tasks",
    ),
]

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeFramedModel
from taggit.managers import TaggableManager


# Create your models here


class Project(models.Model):
    name = models.CharField(max_length=20)
    permitted_users = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Task(TimeFramedModel):
    text = models.CharField(max_length=40)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    tag = TaggableManager(blank=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="created_by"
    )
    assign_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="assigned_to",
    )
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.text

tasks/forms.py
from django.forms import ModelForm, fields
from django.contrib.auth.models import User
from django import forms
from .models import *


class ProjectForm(ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Add new project..."})
    )

    permitted_users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(), required=False
    )

    class Meta:
        model = Project
        fields = "__all__"


class TaskForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Add new task..."})
    )
    end = forms.DateTimeField(
        required=False,
        input_formats=["%Y-%m-%dT%H:%M"],
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local", "class": "form-control"},
            format="%Y-%m-%dT%H:%M",
        ),
    )

    class Meta:
        model = Task
        fields = ["text", "tag", "end", "completed", "assign_to"]

tasks/views.py
import json
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.utils.timezone import now
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import UserPassesTestMixin
from datetime import datetime, timezone
from .models import Project, Task
from .filters import TaskFilter
from django.urls.base import reverse_lazy, reverse
from .forms import TaskForm, ProjectForm
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# Create your views here.


@method_decorator(login_required, name="dispatch")
class ProjectList(ListView):
    template_name = "tasks/project_list_view.html"
    model = Project
    context_object_name = "projects"

    def get_queryset(self):
        return Project.objects.filter(permitted_users=self.request.user)


@method_decorator(login_required, name="dispatch")
class ProjectCreateView(View):
    def post(self, request):
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save()
            project.permitted_users.add(self.request.user)

            return redirect("tasks:list_projects")
        return render(request, "tasks/create_project_view.html", {"form": form})

    def get(self, request):
        form = ProjectForm()
        return render(request, "tasks/create_project_view.html", {"form": form})


@method_decorator(login_required, name="dispatch")
class ProjectUpdateView(
    UserPassesTestMixin,
    UpdateView,
):
    model = Project
    fields = ("name", "permitted_users")
    template_name = "tasks/edit_project_view.html"
    pk_url_kwarg = "pk"
    context_object_name = "project"

    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()

    def form_valid(self, form):
        project = form.save()
        return redirect(
            "tasks:list_projects",
        )


@method_decorator(login_required, name="dispatch")
class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    model = Project
    success_url = reverse_lazy("tasks:list_projects")
    template_name = "tasks/delete_project_view.html"
    pk_url_kwarg = "pk"
    context_object_name = "project"

    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()


@method_decorator(login_required, name="dispatch")
class TaskListView(UserPassesTestMixin, ListView):
    template_name = "tasks/task_list_view.html"
    model = Task
    context_object_name = "tasks"

    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()

    def get_queryset(self):
        return Task.objects.filter(
            project=self.kwargs.get("pk"), assign_to=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = get_object_or_404(Project, pk=self.kwargs.get("pk"))
        context["task_assigned_to_others"] = Task.objects.filter(
            project=self.kwargs.get("pk"), created_by=self.request.user
        ).exclude(assign_to=self.request.user)
        return context


@method_decorator(login_required, name="dispatch")
class TaskCreateView(UserPassesTestMixin, View):
    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()

    def post(self, request, pk):
        self.project = get_object_or_404(Project, pk=pk)
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = self.project
            task.created_by = self.request.user
            if task.assign_to == None:
                task.assign_to = self.request.user
            task.save()
            return redirect(reverse("tasks:list_task", kwargs={"pk": self.project.pk}))
        return render(
            request, "tasks/create_task_view.html", {"form": form, "project_pk": pk}
        )

    def get(self, request, pk):
        form = TaskForm()
        return render(
            request, "tasks/create_task_view.html", {"form": form, "project_pk": pk}
        )


@method_decorator(login_required, name="dispatch")
class TaskUpdateView(UserPassesTestMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update_task_view.html"
    pk_url_kwarg = "task_pk"
    context_object_name = "task"

    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()

    def form_valid(self, form):
        task = form.save()
        return redirect(reverse("tasks:list_task", kwargs={"pk": task.project.pk}))


@login_required
def task_completed_view(request, pk, task_pk):
    if request.is_ajax():
        task = get_object_or_404(Task, pk=task_pk)
        task.completed = not task.completed
        task.save()
    return JsonResponse({"ok": True}, status=200)


@method_decorator(login_required, name="dispatch")
class TaskDeleteView(UserPassesTestMixin, DeleteView):
    model = Task
    template_name = "tasks/delete_task_view.html"
    pk_url_kwarg = "task_pk"
    context_object_name = "task"

    def test_func(self):
        user = self.request.user
        return user.project_set.filter(pk=self.kwargs.get("pk")).exists()

    def get_success_url(self, **kwargs):
        return reverse_lazy("tasks:list_task", kwargs={"pk": self.object.project.pk})


@method_decorator(login_required, name="dispatch")
class TaskOverdueListView(ListView):
    model = Task
    template_name = "tasks/overdue_tasks_view.html"
    context_object_name = "overdue_tasks"

    def get_queryset(self):
        overdue_tasks = Task.objects.filter(
            assign_to=self.request.user,
            end__lte=now(),
            completed=False,
        )
        project = self.kwargs.get("pk", None)

        if project:
            overdue_tasks = overdue_tasks.filter(project=project)

        return overdue_tasks


@method_decorator(login_required, name="dispatch")
class TaskFilterView(ListView):
    model = Task
    template_name = "tasks/tasks_filter_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = TaskFilter(self.request.GET, queryset=self.get_queryset())
        return context

tasks/templates/tasks/all_overdue_tasks_view.html
<div>
    <h2>
        All overdue tasks
    </h2>
</div>
<div>
    {% if overdue_tasks %}
    {% for task in overdue_tasks %}
        <div>
            <a href="{% url 'tasks:update_task' task.project.id task.id %}">{{task}}-{{task.project.name}}</a>
            <span><a href="{% url 'tasks:delete_task' task.project.id task.id%}">delete</a></span>
        </div>
    {% endfor %}
    {% else %}
        <div>No overdue tasks</div>
    {% endif %}
</div>
<div>
    <a href = "{% url 'tasks:list_projects' %}">Go to Projects</a>
</div>

tasks/templates/tasks/create_project_view.html
<div>
  <a href="{% url 'logout' %}">logout</a>
</div>
{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success">Create</button>
  <a href="{% url 'tasks:list_projects' %}" role="button">Cancel</a>
</form>
{% endblock %}

tasks/templates/tasks/create_task_view.html
<div>
  <a href="{% url 'logout' %}">logout</a>
</div>
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Create</button>
    <a href="{% url 'tasks:list_projects' %}" role="button">Cancel</a>
  </form>
{% endblock %}

tasks/templates/tasks/delete_project_view.html
<div>
  <a href="{% url 'logout' %}">logout</a>
</div>
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{project}}?
    <button type="submit" class="btn btn-success">Delete</button>
    <a href="{% url 'tasks:list_projects' %}" role="button">Cancel</a>
  </form>
{% endblock %}

tasks/templates/tasks/delete_task_view.html
<div>
    <a href="{% url 'logout' %}">logout</a>
</div>
  {% block content %}
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete {{task}}?
      <button type="submit" class="btn btn-success">Delete</button>
      <a href="{% url 'tasks:list_task' task.project.id %}" role="button">Cancel</a>
    </form>
  {% endblock %}

tasks/templates/tasks/edit_project_view.html
<div>
  <a href="{% url 'logout' %}">logout</a>
</div>
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'tasks:list_projects' %}">Cancel</a>
  </form>
{% endblock %}

tasks/templates/tasks/overdue_tasks_view.html
<div>
    <a href="{% url 'logout' %}">logout</a>
</div>
<div>
    <h1>Overdue tasks</h1>
    {% for task in overdue_tasks %}
        <div>
            <a href="{% url 'tasks:update_task' task.project.id task.id %}">{{task}}</a>
            <span><a href="{% url 'tasks:delete_task' task.project.id task.id%}">delete</a></span>
        </div>
    {% empty %}
        <div>No overdue tasks</div>
    {% endfor %}
</div>

tasks/templates/tasks/project_list_view.html
<div>
    <a href="{% url 'logout' %}">logout</a>
</div>
<div><h1>List of projects</h1></div>
<hr>
<div>
    {% if projects %}
    {% for project in projects %}
        <div>
            <a href="{% url 'tasks:list_task' project.id%}">{{project}}</a>
            <span><a href="{% url 'tasks:update_project' project.id%}">update</a></span>
            <span><a href="{% url 'tasks:delete_project' project.id%}">delete</a></span>
        </div>
    {% endfor %}
    {% endif %}

</div>

tasks/templates/tasks/task_list_view.html
<head>
    {% load static %}
    {% block scripts %} 
    <div id = "display-tasks">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0-rc.1/dist/js.cookie.min.js"></script>
    <script src="{% static 'tasks/mark_as_complete.js' %}"></script> 
    {% endblock scripts %}
</head>
<div>
    <a href="{% url 'logout' %}">logout</a>
</div>
<div><h1>List of tasks in {{project.name}}</h1></div>
<hr>
<div><a href="{% url 'tasks:create_task' project.id %}">Create Task</a></div>
<hr>
<div>
    {% if tasks %}
    {% for task in tasks %}
        <div>
            <a href="{% url 'tasks:update_task' project.id task.id %}">{{task}}</a>
            <span><a href="{% url 'tasks:delete_task' project.id task.id %}">delete</a></span>
            | Completed: <input {% if task.completed %} checked="checked" {% endif %}type="checkbox" value = "{{ task.completed }}" onclick="updateField({{ task.pk }})">
        </div>
    {% endfor %}
    {% endif %}
    <hr>
    <div>
        Tasks assigned to others by you
    </div>

    {% for task in task_assigned_to_others %}
    <div>
            <a href="{% url 'tasks:update_task' project.id task.id %}">{{task}}</a>
            <span><a href="{% url 'tasks:delete_task' project.id task.id %}">delete</a></span>
            -- Assigned to {{task.assign_to}}
    </div>
    {% empty %}
    <div>
        No tasks to show
    </div>
    {% endfor %}



</div>

tasks/templates/tasks/tasks_filter_view.html
<div>
    <a href="{% url 'logout' %}">logout</a>
</div>
<div><h1>Search Tasks View<h1></div>
    <div>
        <form method = "GET" novalidate>
            {% csrf_token %}
            Task:
            {{ filter.form.text }}
            Project:
            {{filter.form.project}}
            Overdue after
            <input type="date" {{filter.form.end__date__lte}}
            <button type="submit" class="btn btn-success">Search</button>
        </form>
    
        <ul>
            {% for task in filter.qs %}
            
            <li>
                <div>
                    <a href="{% url 'tasks:update_task' task.project.id task.id %}">{{task}} - {{task.project.name}} - 
                        {% if task.completed %}
                        Completed
                        {% else %}
                        Not completed
                        {% endif %}
                    </a>
                    <span><a href="{% url 'tasks:delete_task' task.project.id task.id%}">| delete</a></span>
                </div>
            </li>
            {% endfor %}
        </ul>
    
    </div>

tasks/templates/tasks/update_task_view.html
<div>
  <a href="{% url 'logout' %}">logout</a>
</div>
{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success">Save changes</button>
  <a href="{% url 'tasks:list_task' task.project.id %}" role="button">Cancel</a>
</form>
{% endblock %}